baseURL = "https://sam-barrett.codes/Y4-Diss/"
languageCode = "en-us"
title = "My Dissertation Blog"
publishDir = "../docs"
theme="ananke"
staticDir = "./static"


[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
