baseURL = "/Y4-Diss/"
languageCode = "en-us"
title = "My Final Year Project Blog"
publishDir = "../docs"
theme="ananke"
staticDir = "./static"


[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
